travis:
  secure:
    BINSTAR_TOKEN: RDQpnQwuvuhMxOlHK58QJmxVuxinBuogZledoUyK58blx6WNfLZ6psFxDdCjjqoWmAFYh5/1wM/l1coqXN55N+YccYKAeva2jjPzS9mXDbjYeuvGjIvVBkY4vyLv4DTTkIXNEiV4rexf2O57LVZ7AqQtSuBChMqxGjuqQ3cPIBK7PDf1DjQ4O8HQNbUxCCgs2Sm/rVNjcplxvLNmEviZ31Qmvy+QblXBWY8aQWne1TG4r79mFxLCPUZ6fQSu/+sD7JtargPq6XpzM9f4NbjgT70aKD10YbErWsQHbL+AMONioXvPlmDpR7pquKFkKOnpJ7ETZAkm7hw2REXohH/JgeVq+1hU0xane9PQLz0gW/iDcVaYO+FCulUeTPolHDv0zTG14OntT84ZG8/Rrhr+qLV/CkYpeaIYu5CF+R4Idy4li3GshsUe86LUklTxQq1uN9nPIRF6pUH9sk5YmKObRxJ6sLdE523OI6dZOZg4WBcZnf7N+9hyBlZXjd2NN4wkH59AcERp0IBrDE7XNwyCw8Xp0fLxODvDliNP81t4XWuiny4jMs4Jvgtdj1shxyiWAuVOkMXFccl6pG6I2sbu2u8j4yeRTmwqZtQriYqN2OLGyMg6O/ZsJLKogxT+FrFEzQns/Rx3spVs1F2QOBgG2cm/oAo0l6wxLAOVS6j8J5k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
channels:
  targets:
  - [conda-forge, dev]
provider:
  win: azure
conda_forge_output_validation: true
